<?xml version="1.0"?>
<package format="3">
  <name>robotics_language_lab</name>
  <version>0.1.0</version>
  <description>ROS 2-style practice package for a small multi-language robotics lab.</description>
  <maintainer email="example@example.com">Radwan Abdulhadi Ahmed</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
